# Generated by Django 2.2.13 on 2020-09-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='单词')),
                ('mean', models.CharField(max_length=500, verbose_name='解释')),
            ],
            options={
                'db_table': 'word',
            },
        ),
    ]
