# Generated by Django 2.2.13 on 2020-09-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nper', models.CharField(max_length=20, verbose_name='期号')),
                ('red_one', models.CharField(max_length=10, verbose_name='红1')),
                ('red_two', models.CharField(max_length=10, verbose_name='红2')),
                ('red_three', models.CharField(max_length=10, verbose_name='红3')),
                ('red_four', models.CharField(max_length=10, verbose_name='红4')),
                ('red_five', models.CharField(max_length=10, verbose_name='红5')),
                ('red_six', models.CharField(max_length=10, verbose_name='红6')),
                ('blue', models.CharField(max_length=10, verbose_name='蓝球')),
                ('time', models.CharField(max_length=20, verbose_name='开奖日期')),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
