# Generated by Django 2.2.13 on 2020-09-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='', max_length=10, verbose_name='地区名称')),
                ('number', models.CharField(default=0, max_length=20, verbose_name='地区编号')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
